CREATE OR REPLACE FUNCTION PUBLIC.OBTENER_CANTIDAD_SESIONES () RETURNS BIGINT LANGUAGE PLPGSQL AS $$
DECLARE
	TOTAL BIGINT;
BEGIN
	SELECT COUNT(*) INTO TOTAL FROM PUBLIC.SEARCH_SESSION;
	RETURN TOTAL;
END;
$$;

CREATE OR REPLACE FUNCTION PUBLIC.OBTENER_CANTIDAD_RECURSOS_CALIFICADOS () RETURNS BIGINT LANGUAGE PLPGSQL AS $$
DECLARE
	TOTAL BIGINT;
BEGIN
	SELECT COUNT(*) INTO TOTAL FROM PUBLIC.TASK_SESSION_RESOURCE WHERE PERTINENCE_SCORE IS NOT NULL;
	RETURN TOTAL;
END;
$$;

CREATE OR REPLACE FUNCTION PUBLIC.OBTENER_PROMEDIO_TIEMPO_SESION () RETURNS NUMERIC LANGUAGE PLPGSQL AS $$
DECLARE
	TOTAL NUMERIC;
BEGIN
	SELECT ROUND(AVG(EXTRACT(EPOCH FROM (END_AT - START_AT)) / 60), 2) INTO TOTAL FROM PUBLIC.TASK_SESSION;
	RETURN TOTAL;
END;
$$;

CREATE OR REPLACE FUNCTION PUBLIC.OBTENER_PROMEDIO_RECURSOS_CALIFICADOS () RETURNS NUMERIC LANGUAGE PLPGSQL AS $$
DECLARE
	TOTAL NUMERIC;
BEGIN
	SELECT ROUND(AVG(CONTEO), 2)
	INTO TOTAL
	FROM (
		SELECT TASK_SESSION_ID, COUNT(*) AS CONTEO
		FROM PUBLIC.TASK_SESSION_RESOURCE 
		WHERE PERTINENCE_SCORE IS NOT NULL 
		GROUP BY TASK_SESSION_ID
	);
	RETURN TOTAL;
END;
$$;