SELECT
	A.RESOURCE_ID,
	A.PROMEDIO_PERTINENCE,
	B.PROMEDIO_CLICKS,
	B.PROMERIO_TIEMPO_HASTA_ENCONTRAR
FROM
	(
		SELECT
			RESOURCE_ID,
			AVG(PERTINENCE_SCORE) AS PROMEDIO_PERTINENCE,
			COUNT(*) AS CANTIDAD,
			MAX(INDEX) AS MAX_INDEX
		FROM
			PUBLIC.TASK_SESSION_RESOURCE
		WHERE
			PERTINENCE_SCORE IS NOT NULL
		GROUP BY
			RESOURCE_ID
		ORDER BY
			PROMEDIO_PERTINENCE DESC,
			CANTIDAD DESC,
			MAX_INDEX DESC
	) A
	INNER JOIN (
		SELECT
			RESOURCE_ID,
			AVG(FILAS_ANTES) AS PROMEDIO_CLICKS,
			AVG(TIEMPO_HASTA_ENCONTRAR) AS PROMERIO_TIEMPO_HASTA_ENCONTRAR
		FROM
			(
				SELECT
					A.RESOURCE_ID,
					ROW_NUMBER() OVER (
						PARTITION BY
							A.TASK_SESSION_ID
						ORDER BY
							A.NAVIGATED_AT
					) - 1 AS FILAS_ANTES,
					A.NAVIGATED_AT - B.START_AT AS TIEMPO_HASTA_ENCONTRAR
				FROM
					PUBLIC.TASK_SESSION_RESOURCE A
					INNER JOIN PUBLIC.TASK_SESSION B ON A.TASK_SESSION_ID = B.ID
				ORDER BY
					TASK_SESSION_ID,
					NAVIGATED_AT
			)
		GROUP BY
			RESOURCE_ID
	) B ON A.RESOURCE_ID = B.RESOURCE_ID
ORDER BY
	A.PROMEDIO_PERTINENCE DESC,
	A.CANTIDAD DESC,
	A.MAX_INDEX DESC;