SELECT
	A.PROMEDIO_PERTINENCIA,
	C.NUM_MICRODATA,
	C.NUM_MICROFORMATS,
	C.NUM_RDFA,
	C.NUM_JSONLD,
	C.NUM_VOCABULARIES,
	C.NUM_ONTOLOGIES,
	C.NUM_DATASETS,
	C.FAIR_SCORE,
	C.F1_SCORE,
	C.F2_SCORE,
	C.F3_SCORE,
	C.F4_SCORE,
	C.I1_SCORE,
	C.I2_SCORE,
	C.I3_SCORE,
	C.SEO_SCORE,
	C.ACCESIBILITY_SCORE,
	C.PERFORMANCE_SCORE
FROM
	(
		SELECT
			RESOURCE_ID,
			AVG(PERTINENCE_SCORE) AS PROMEDIO_PERTINENCIA
		FROM
			PUBLIC.TASK_SESSION_RESOURCE
		WHERE
			PERTINENCE_SCORE IS NOT NULL
		GROUP BY
			RESOURCE_ID
	) A
	INNER JOIN PUBLIC.RESOURCE B ON A.RESOURCE_ID = B.ID
	INNER JOIN PUBLIC.AUTOMATIC_EVALUATION C ON B.AUTOMATIC_EVALUATION_ID = C.ID
ORDER BY
	A.PROMEDIO_PERTINENCIA DESC;